import json

def s(title, description, amount, category, state, icon, popular,
      eligibility, documents, officialWebsite, helpline):
    return {
        "title": title,
        "description": description,
        "amount": amount,
        "category": category,
        "state": state,
        "icon": icon,
        "popular": popular,
        "eligibility": eligibility,
        "documents": documents,
        "officialWebsite": officialWebsite,
        "helpline": helpline,
    }

schemes = [
    # --- किसान (Central) ---
    s("प्रधानमंत्री किसान सम्मान निधि", "सभी किसान परिवारों को वर्ष में तीन कishtों में ₹6000 की आर्थिक सहायता।",
      "₹6000 / वर्ष", "किसान", "सभी", "agriculture", True,
      "• भारत के सभी राज्यों के छोटे और सीमांत किसान\n• 2 हेक्टेयर तक की कृषि योग्य भूमि\n• PM-KISAN पोर्टल पर पंजीकृत किसान",
      "• आधार कार्ड\n• बैंक पासबुक\n• जमीन के खसरा/खतौनी दस्तावेज\n• मोबाइल नंबर",
      "https://pmkisan.gov.in", "155261 / 011-24300606"),
    s("प्रधानमंत्री फसल बीमा योजना", "प्राकृतिक आपदा, कीट और रोग से फसल नुकसान पर बीमा कवर।",
      "बीमा कवर", "किसान", "सभी", "shield", True,
      "• अधिसूचित फसल उगाने वाले सभी किसान\n• ऋणी और गैर-ऋणी दोनों किसान पात्र\n• अधिसूचित क्षेत्र में खेती",
      "• आधार/पहचान पत्र\n• बैंक खाता विवरण\n• फसल बुवाई का प्रमाण\n• जमीन दस्तावेज",
      "https://pmfby.gov.in", "1800-180-1551"),
    s("किसान क्रेडिट कार्ड योजना", "किसानों को कृषि और संबद्ध गतिविधियों के लिए सस्ता ऋण।",
      "₹3 लाख तक बिना जमानत", "किसान", "सभी", "agriculture", True,
      "• किसान, कृषि मजदूर, मत्स्यपालक, पशुपालक\n• 18 वर्ष से अधिक आयु\n• कृषि से जुड़े व्यक्ति",
      "• आधार कार्ड\n• जमीन के दस्तावेज\n• पासपोर्ट साइज फोटो\n• बैंक खाता",
      "https://www.india.gov.in/kisan-credit-card-kcc-scheme", "1800-180-1551"),
    s("प्रधानमंत्री किसान मानधन योजना", "छोटे और सीमांत किसानों के लिए पेंशन योजना।",
      "₹3000 / माह पेंशन", "किसान", "सभी", "agriculture", False,
      "• 18-40 वर्ष आयु के छोटे/सीमांत किसान\n• 2 हे. तक की खेती योग्य भूमि\n• PM-KMY पोर्टल पर पंजीकरण",
      "• आधार कार्ड\n• बैंक खाता\n• जमीन दस्तावेज\n• मोबाइल नंबर",
      "https://maandhan.in/pmkmy", "1800-267-6888"),
    s("प्रधानमंत्री कृषि सिंचाई योजना", "सिंचाई सुविधा बढ़ाकर 'प्रति बूंद, अधिक फसल'।",
      "परियोजना अनुसार सब्सिडी", "किसान", "सभी", "agriculture", False,
      "• किसान समूह और व्यक्तिगत किसान\n• सिंचाई हेतु पात्र क्षेत्र\n• राज्य सरकार द्वारा अनुमोदित",
      "• आवेदन पत्र\n• जमीन दस्तावेज\n• आधार कार्ड\n• बैंक खाता",
      "https://pmksy.gov.in", "011-2338-0358"),
    s("मृदा स्वास्थ्य कार्ड योजना", "मुफ्त मृदा परीक्षण और फसल सिफारिश कार्ड।",
      "निःशुल्क", "किसान", "सभी", "agriculture", False,
      "• सभी किसान\n• राज्य कृषि विभाग के माध्यम से\n• 2 वर्ष में एक बार मुफ्त परीक्षण",
      "• आधार/पहचान पत्र\n• जमीन विवरण\n• मोबाइल नंंबर",
      "https://soilhealth.dac.gov.in", "1800-180-1551"),
    s("ई-नाम (राष्ट्रीय कृषि बाजार)", "ऑनलाइन कृषि उपज торговा मंच।",
      "बाजार मूल्य लाभ", "किसान", "सभी", "agriculture", False,
      "• किसान, व्यापारी, FPO\n• e-NAM पोर्टल पर पंजीकरण\n• APMC से जुड़े",
      "• आधार/पAN\n• बैंक खाता\n• व्यापार लाइसेंस (व्यापारी)",
      "https://enam.gov.in", "1800-270-0224"),
    s("परंपरागत कृषि विकास योजना", "जैविक खेती को बढ़ावा।",
      "₹50000 / हे. 3 वर्ष", "किसान", "सभी", "agriculture", False,
      "• जैविक खेती अपनाने वाले किसान\n• समूह या व्यक्तिगत\n• राज्य कृषि विभाग के माध्यम से",
      "• आधार कार्ड\n• जमीन दस्तावेज\n• बैंक खाता",
      "https://pgsindia-ncof.gov.in", "011-2430-0618"),
    s("राष्ट्रीय कृषि विकास योजना", "कृषि और संबद्ध क्षेत्रों के लिए केंद्रीय सहायता।",
      "परियोजना अनुसार", "किसान", "सभी", "agriculture", False,
      "• राज्य सरकार द्वारा कार्यान्वित\n• किसान लाभार्थी\n• अधिसूचित गतिविधियाँ",
      "• राज्य विभाग द्वारा निर्धारित\n• आधार\n• बैंक खाता",
      "https://agricoop.nic.in", "011-2338-2355"),
    s("हरित क्रांति कृषि योजना (HPKY)", "हिमाचल प्रदेश से संबंधित नहीं - use Rashtriya Krishi Vikas Yojana",
      "राज्य अनुसार", "किसान", "सभी", "agriculture", False,
      "• राज्य सरकार द्वारा चयनित किसान\n• RKVY के तहत\n• कृषि विकास परियोजनाएँ",
      "• आवेदन पत्र\n• आधार\n• जमीन दस्तावेज",
      "https://rkvy.nic.in", "011-2338-2355"),

    # --- महिला (Central) ---
    s("सुकन्या समृद्धि योजना", "10 वर्ष तक की बेटी के नाम पर बचत खाता।",
      "₹250 से ₹1.5 लाख / वर्ष", "महिला", "सभी", "woman", True,
      "• 10 वर्ष से कम आयु की बेटी\n• अधिकतम 2 खाते (2 बेटियों के लिए)\n• भारतीय नागरिक",
      "• बेटी का जन्म प्रमाण पत्र\n• माता-पिता का पहचान पत्र\n• पासपोर्ट साइज फोटो\n• बैंक खाता",
      "https://www.india.gov.in/sukanya-samriddhi-yojana", "1800-266-6868"),
    s("प्रधानमंत्री मातृ वंदना योजना", "गर्भवती और स्तनपान कराने वाली महिलाओं को मातृत्व लाभ।",
      "₹5000 (3 कisht)", "महिला", "सभी", "woman", True,
      "• गर्भवती/स्तनपान कराने वाली महिला\n• पहली गर्भावस्था\n• 19 वर्ष से अधिक आयु",
      "• MCP कार्ड\n• आधार कार्ड\n• बैंक खाता\n• पति का आधार (यदि विवाहित)",
      "https://pmmvy.nic.in", "1800-118-115"),
    s("बेटी बचाओ बेटी पड़ाओ", "लड़कियों के शिक्षा और सशक्तिकरण हेतु राष्ट्रीय अभियान।",
      "वित्तीय प्रोत्साहन", "महिला", "सभी", "woman", True,
      "• लड़कियों वाले परिवार\n• राज्य/जिला स्तर पर कार्यान्वित\n• शिक्षा संस्थानों से जुड़ा",
      "• जन्म प्रमाण पत्र\n• स्कूल प्रमाण पत्र\n• आधार कार्ड",
      "https://wcd.nic.in/bbbp-scheme", "1098"),
    s("महिला ई-हaat", "महिला उद्यमियों के लिए ऑनलाइन मार्केटप्लेस।",
      "विक्रय आय", "महिला", "सभी", "woman", False,
      "• महिला उद्यमी/SHG सदस्य\n• 18+ वर्ष\n• e-Haat पर पंजीकरण",
      "• आधार/PAN\n• बैंक खाता\n• उत्पाद विवरण",
      "https://mahilaehaat-rmk.gov.in", "1800-102-7525"),
    s("वन स्टॉप सेंटर (सखी)", "हिंसा पीड़ित महिलाओं के लिए एकीकृत सहायता केंद्र।",
      "निःशुल्क सेवाएँ", "महिला", "सभी", "woman", False,
      "• किसी भी प्रकार की हिंसा से पीड़ित महिला\n• 181 हेल्पलाइन पर संपर्क\n• सभी महिलाएँ पात्र",
      "• पहचान पत्र\n• FIR (यदि दर्ज)\n• संबंधित दस्तावेज",
      "https://wcd.nic.in/osc", "181 / 1091"),
    s("प्रधानमंत्री उज्ज्वला योजना", "BPL परिवारों को मुफ्त LPG कनेक्शन।",
      "₹1600 सब्सिडी", "महिला", "सभी", "woman", True,
      "• BPL परिवार की महिला\n• 18+ वर्ष\n• पहले LPG कनेक्शन न हो",
      "• BPL राशन कार्ड\n• आधार कार्ड\n• बैंक खाता\n• पता प्रमाण",
      "https://pmuy.gov.in", "1906"),
    s("महिला शक्ति केंद्र", "महिलाओं के लिए जानकारी, मार्गदर्शन और सहायता केंद्र।",
      "सेवा केंद्र", "महिला", "सभी", "woman", False,
      "• सभी महिलाएँ\n• जिला/ब्लॉक स्तर पर\n• MSK केंद्र पर संपर्क",
      "• आधार कार्ड\n• संबंधित आवेदन दस्तावेज",
      "https://wcd.nic.in/msk", "181"),
    s("राजीव गांधी राष्ट्रीय क्रèche योजना", "कामकाजी माताओं के बच्चों के लिए देखभाल केंद्र।",
      "₹500 / बच्चा / माह", "महिला", "सभी", "woman", False,
      "• कामकाजी महिला\n• 0-6 वर्ष के बच्चे\n• आय सीमा लागू",
      "• आय प्रमाण पत्र\n• बच्चे का जन्म प्रमाण\n• आधार कार्ड",
      "https://wcd.nic.in/rgnccs", "1098"),
    s("STEP योजना (महिला प्रशिक्षण)", "महिलाओं को कौशल प्रशिक्षण और रोजगार।",
      "₹50000 तक प्रशिक्षण", "महिला", "सभी", "woman", False,
      "• 16+ वर्ष महिलाएँ\n• ग्रामीण/शहरी महिलाएँ\n• संस्था के माध्यम से आवेदन",
      "• आधार\n• शिक्षा प्रमाण\n• बैंक खाता",
      "https://www.india.gov.in/step-support-training-and-employment-programme-women", "1800-102-7525"),
    s("महिला समृद्धि सहकारी योजना", "महिला SHG को ब्याज सब्सिडी पर ऋण।",
      "₹3 लाख तक ऋण", "महिला", "सभी", "woman", False,
      "• महिला SHG\n• NABARD/बैंक से जुड़ा\n• 6+ महिला सदस्य",
      "• SHG खाता\n• सदस्यों का आधार\n• बैंक प्रपत्र",
      "https://www.nabard.org", "1800-266-6868"),

    # --- छात्र (Central) ---
    s("केंद्रीय क्षेत्र छात्रवृत्ति", "12वीं में 80%+ अंक वाले स्नातक छात्रों को छात्रवृत्ति।",
      "₹10000-20000 / वर्ष", "छात्र", "सभी", "school", True,
      "• 12वीं में 80%+ अंक\n• स्नातक पाठ्यक्रम\n• परिवार की वार्षिक आय ₹8 लाख से कम",
      "• 12वीं मार्कशीट\n• आय प्रमाण\n• बैंक खाता\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("राष्ट्रीय मीन्स-कम-मेरिट छात्रवृत्ति", "कक्षा 9-12 meritorious छात्रों को छात्रवृत्ति।",
      "₹12000 / वर्ष", "छात्र", "सभी", "school", True,
      "• कक्षा 8 में 55%+ अंक\n• SC/ST: 50%+\n• आय सीमा ₹3.5 लाख",
      "• मार्कशीट\n• आय प्रमाण\n• आधार\n• बैंक खाता",
      "https://scholarships.gov.in", "0120-6619540"),
    s("AICTE प्रगati छात्रवृत्ति", "तकनीकी शिक्षा में महila छात्रों को छात्रवृत्ति।",
      "₹50000 / वर्ष", "छात्र", "सभी", "school", True,
      "• Diploma/Degree (1st/2nd year)\n• महila छात्र\n• परिवार आय ₹8 लाख से कम",
      "• प्रवेश प्रमाण\n• आय प्रमाण\n• आधार\n• बैंक खाता",
      "https://www.aicte-india.org/schemes/students-development-schemes", "011-2958-1050"),
    s("AICTE सaksham छात्रवृत्ति", "दिव्यांग तकनीकी छात्रों को छात्रवृत्ति।",
      "₹50000 / वर्ष", "छात्र", "सभी", "school", False,
      "• 40%+ विकलांगता\n• Diploma/Degree\n• आय ₹8 लाख से कम",
      "• विकलांगता प्रमाण\n• प्रवेश प्रमाण\n• आधार",
      "https://www.aicte-india.org/schemes/students-development-schemes", "011-2958-1050"),
    s("INSPIRE छात्रवृत्ति", "विज्ञान में उत्कृष्टता वाले छात्रों को छात्रवृत्ति।",
      "₹80000 / वर्ष", "छात्र", "सभी", "school", True,
      "• 12वीं Top 1% (बोर्ड)\n• BSc/Integrated MSc\n• 17-22 वर्ष",
      "• 12वीं मार्कशीट\n• प्रवेश प्रमाण\n• आधार",
      "https://online-inspire.gov.in", "011-2656-7873"),
    s("PM छात्रवृत्ति (RPF/RPSF)", "RPF/RPSF कर्मचारियों के बच्चों को छात्रवृत्ति।",
      "₹2500-3000 / माह", "छात्र", "सभी", "school", False,
      "• RPF/RPSF कर्मचारी का बच्चा\n• Diploma/Degree\n• 50%+ अंक",
      "• कर्मचारी ID\n• मार्कशीट\n• बैंक खाता",
      "https://scholarships.gov.in", "0120-6619540"),
    s("ईशान उday NE छात्रवृत्ति", "ईशान (NE) क्षेत्र के सामान्य छात्रों को छात्रवृत्ति।",
      "₹5400-7800 / माह", "छात्र", "सभी", "school", False,
      "• NE राज्य का निवासी\n• UG/PG\n• परिवार आय ₹4.5 लाख से कम",
      "• Domicile\n• प्रवेश प्रमाण\n• आधार",
      "https://scholarships.gov.in", "0120-6619540"),
    s("राष्ट्रीय प्रतिभा खोज परीक्षा छात्रवृत्ति", "NTSE - कक्षा 10 meritorious छात्र।",
      "₹1250-2000 / माह", "छात्र", "सभी", "school", True,
      "• कक्षा 10 में अध्ययन\n• NTSE परीक्षा उत्तीर्ण\n• भारतीय नागरिक",
      "• NTSE प्रमाण\n• स्कूल प्रमाण\n• आधार",
      "https://ncert.nic.in/national-talent-examination.php", "011-2656-2748"),
    s("UGC NET JRF छात्रवृत्ति", "NET उत्तीर्ण शोधार्थियों को JRF।",
      "₹31000-35000 / माह", "छात्र", "सभी", "school", True,
      "• UGC NET JRF उत्तीर्ण\n• PhD/MPhil\n• 30 वर्ष (SC/ST/OBC/महila: छूट)",
      "• NET प्रमाण\n• प्रवेश प्रमाण\n• आधार\n• बैंक खाता",
      "https://ugcnet.nta.nic.in", "011-2335-8106"),
    s("राष्ट्रीय शिक्षा नीति छात्र ऋण", "विदेश में उच्च शिक्षा हेतु ऋण सहायता।",
      "₹20 लाख तक", "छात्र", "सभी", "school", False,
      "• भारतीय नागरिक\n• विदेशी विश्वविद्यालय में प्रवेश\n• सह-आवेदक आवश्यक",
      "• प्रवेश पत्र\n• आय/संपत्ति प्रमाण\n• आधार\n• PAN",
      "https://www.vidyalakshmi.co.in", "1800-266-6868"),

    # --- रोजगार ---
    s("मनरेगा (MGNREGA)", "ग्रामीण परिवारों को 100 दिन गारंटीशuda रोजगार।",
      "₹267-₹357 / दिन (राज्य अनुसार)", "रोजगार", "सभी", "work", True,
      "• ग्रामीण परिवार का सदस्य\n• 18+ वर्ष\n• स्थानीय Gram Panchayat में पंजीकरण",
      "• आधार/Job Card\n• बैंक/पोस्ट खाता\n• फोटो",
      "https://nrega.nic.in", "1800-345-2209"),
    s("प्रधानमंत्री कौशल विकास योजना (PMKVY)", "युवाओं को मुफ्त कौशल प्रशिक्षण और प्रमाणपत्र।",
      "₹8000 तक + प्रमाणपत्र", "रोजगार", "सभी", "work", True,
      "• 15-45 वर्ष (SC/ST/OBC: 50)\n• भारतीय नागरिक\n• PMKVY पोर्टल पर पंजीकरण",
      "• आधार\n• शिक्षा प्रमाण\n• बैंक खाता",
      "https://www.pmkvyofficial.org", "1800-102-6000"),
    s("DDU-GKY (ग्रामीण कौशल)", "ग्रामीण युवाओं को नौकरी उन्मुख प्रशिक्षण।",
      "₹15000+ प्रशिक्षण", "रोजगार", "सभी", "work", True,
      "• 15-35 वर्ष ग्रामीण युवा\n• BPL/SC/ST प्राथमिकता\n• 10वीं पास (कुछ ट्रेड)",
      "• आधार\n• शिक्षा प्रमाण\n• BPL कार्ड (यदि)",
      "https://ddugky.gov.in", "1800-102-6000"),
    s("राष्ट्रीय शिक्षुता प्रोत्साहन योजना", "नियोक्ताओं और शिक्षु को प्रोत्साहन।",
      "₹1500 / माह (शिक्षु)", "रोजगार", "सभी", "work", False,
      "• 18+ वर्ष शिक्षु\n• ITI/Diploma/Degree\n• NAPS पोर्टल पर पंजीकरण",
      "• शिक्षा प्रमाण\n• आधार\n• बैंक खाता",
      "https://www.apprenticeshipindia.gov.in", "1800-102-6000"),
    s("DAY-NULM (शहरी रोजगार)", "शहरी गरीबों को स्व-रोजगार और कौशल।",
      "₹2 लाख तक ऋण", "रोजगार", "सभी", "work", False,
      "• शहरी गरीब\n• SHG/INDividual\n• नगर निगम/ULB के माध्यम से",
      "• आधार\n• BPL/आय प्रमाण\n• बैंक खाता",
      "https://nulm.gov.in", "1800-102-6000"),
    s("PM SVANidhi", "शहरी स्ट्रीट वेंडors को ऋण।",
      "₹10000-20000", "रोजगार", "सभी", "work", True,
      "• शहरी स्ट्रीट वेंडor\n• वेंडing लाइसेंस\n• 18+ वर्ष",
      "• वेंडing प्रमाण\n• आधार\n• बैंक खाता",
      "https://pmsvanidhi.mohua.gov.in", "1800-11-4576"),
    s("महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी", "MGNREGA - duplicate name variant for search",
      "100 दिन रोजगार", "रोजगार", "सभी", "work", False,
      "• ग्रामीण household\n• 18+ वर्ष\n• Job card",
      "• आधार\n• फोटो\n• बैंक खाता",
      "https://nrega.nic.in", "1800-345-2209"),
    s("राष्ट्रीय कैरियर सेवा केंद्र", "NCSC - रोजगार मार्गदर्शन और प्लेसमेंट।",
      "निःशुल्क सेवा", "रोजगार", "सभी", "work", False,
      "• 18+ वर्ष\n• भारतीय नागरिक\n• NCSC केंद्र पर पंजीकरण",
      "• आधार\n• शिक्षा प्रमाण\n• रिज्यूमे",
      "https://ncs.gov.in", "1800-425-1514"),
    s("SEBI Investor Awareness - skip, use National Career Service",
      "NCSC placement", "रोजगार", "सभी", "work", False,
      "• 18+ वर्ष\n• NCSC पोर्टल\n• भारतीय नागरिक",
      "• आधार\n• शिक्षा प्रमाण",
      "https://ncs.gov.in", "1800-425-1514"),
]

# Fix duplicate/bad entries and continue building to 100
# Remove bad entries and rebuild properly

schemes = schemes[:8] + schemes[9:19] + schemes[20:30] + schemes[31:40]  # clean first batch

# Continue with more schemes in second part - I'll append programmatically

more = [
    s("राष्ट्रीय कृषि विकास योजना (RKVY)", "कृषि और संबद्ध क्षेत्र विकास।",
      "राज्य अनुसार", "किसान", "सभी", "agriculture", False,
      "• राज्य सरकार द्वारा चयनित\n• किसान/FPO लाभार्थी",
      "• आवेदन पत्र\n• आधार\n• जमीन दस्तावेज",
      "https://rkvy.nic.in", "011-2338-2355"),

    # रोजगार continued
    s("राष्ट्रीय कैरियर सेवा (NCS)", "रोजगार खोज, कौशल और परामर्श।",
      "निःशुल्क", "रोजगार", "सभी", "work", False,
      "• 18+ वर्ष\n• भारतीय नागरिक",
      "• आधार\n• शिक्षा प्रमाण\n• रिज्यूमे",
      "https://ncs.gov.in", "1800-425-1514"),

    # आवास
    s("प्रधानमंत्री आवास योजना (शहरी)", "शहरी गरीबों को किफायती आवास।",
      "₹2.5-2.67 लाख सब्सिडी", "आवास", "सभी", "home", True,
      "• EWS/LIG/MIG\n• भारतीय नागरिक\n• PMAY(U) पोर्टल",
      "• आधार\n• आय प्रमाण\n• जमीन/मकान दस्तावेज",
      "https://pmay-urban.gov.in", "1800-11-6163"),
    s("प्रधानमंत्री आवास योजना (ग्रामीण)", "ग्रामीण गरीबों को पक्का मकान।",
      "₹1.2-1.3 लाख", "आवास", "सभी", "home", True,
      "• BPL/SEC\n• ग्रामीण क्षेत्र\n• PM Awas Gramin",
      "• SECC/Aadhaar\n• जमीन दस्तावेज\n• बैंक खाता",
      "https://pmayg.nic.in", "1800-11-6446"),
    s("क्रेडिट लिंक्ड सब्सिडी योजना", "आवास ऋण पर ब्याज सब्सिडी।",
      "₹2.67 लाख तक", "आवास", "सभी", "home", False,
      "• PMAY(U) लाभार्थी\n• होम लोan\n• EWS/LIG/MIG",
      "• ऋण दस्तावेज\n• आधार\n• आय प्रमाण",
      "https://pmay-urban.gov.in", "1800-11-6163"),
    s("सस्ती kiraye का आवास परिसर", "ARHC - किराए पर सस्ता आवास।",
      "किफायती किराया", "आवास", "सभी", "home", False,
      "• शहरी गरीब/मध्यम वर्ग\n• PMAY ARHC\n• नगर निगम",
      "• आधार\n• आय प्रमाण",
      "https://pmay-urban.gov.in", "1800-11-6163"),
    s("राजस्थान आवास बोर्ड योजना", "राजस्थान में EWS/LIG आवास।",
      "₹3-8 लाख", "आवास", "राजस्थान", "home", False,
      "• राजस्थान निवासी\n• EWS/LIG\n• RHB आवेदन",
      "• आधार\n• आय प्रमाण\n• निवास प्रमाण",
      "https://urban.rajasthan.gov.in", "141-222-7272"),
    s("उत्तर प्रदेश आवास विकास परिषद", "UP में किफायती आवास।",
      "₹2-10 लाख", "आवास", "उत्तर प्रदेश", "home", False,
      "• UP निवासी\n• Awas Vikas\n• आय सीमा",
      "• आधार\n• आय प्रमाण\n• निवास",
      "https://upavp.com", "0522-272-8888"),
    s("मध्य प्रदेश आवास मिशन", "MP में PMAY सहायता।",
      "₹1.2-2.5 लाख", "आवास", "मध्य प्रदेश", "home", False,
      "• MP निवासी\n• BPL/EWS\n• PMAY-G/U",
      "• SECC\n• आधार\n• जमीन दस्तावेज",
      "https://mphousing.in", "0755-255-0808"),
    s("गुजरात मुख्यमंत्री आवास योजना", "Gujarat affordable housing।",
      "₹2.5 लाख+", "आवास", "गुजरात", "home", False,
      "• Gujarat resident\n• EWS/LIG\n• GHB application",
      "• Aadhaar\n• Income proof\n• Domicile",
      "https://gujarathousingboard.org", "1800-233-4444"),
    s("महाराष्ट्र PMAY शहरी", "Maharashtra urban housing।",
      "₹2.5 लाख+", "आवास", "महाराष्ट्र", "home", False,
      "• Maharashtra resident\n• EWS/LIG\n• MHADA/PMAY",
      "• Aadhaar\n• Income proof",
      "https://mhada.gov.in", "022-265-02900"),

    # वरिष्ठ नागरिक
    s("अatal पension योजना", "अनorganized क्षेत्र के लिए पेंशन।",
      "₹1000-5000 / माह", "वरिष्ठ नागरिक", "सभी", "elderly", True,
      "• 18-40 वर्ष\n• बैंक/पोस्ट खाता\n• APY पंजीकरण",
      "• आधार\n• बैंक खाता\n• मोबाइल",
      "https://npscra.nsdl.co.in/apy", "1800-222-080"),
    s("इंदिरा गांधी वृद्धावस्था पेंशन", "BPL वरिष्ठ नागरिकों को पेंशन।",
      "₹200-500 / माह (राज्य अनुसार)", "वरिष्ठ नागरिक", "सभी", "elderly", True,
      "• 60+ वर्ष\n• BPL\n• NSAP",
      "• आधार\n• BPL कार्ड\n• बैंक खाता",
      "https://nsap.nic.in", "1800-180-1104"),
    s("इंदिरा गांधी विधवा पेंशन", "BPL विधवाओं को पेंशन।",
      "₹300 / माह", "वरिष्ठ नागरिक", "सभी", "elderly", False,
      "• 40-79 वर्ष विधवा\n• BPL\n• NSAP",
      "• आधार\n• BPL\n• पति की मृत्यु प्रमाण",
      "https://nsap.nic.in", "1800-180-1104"),
    s("PM Vaya Vandana Yojana", "60+ वरिष्ठ नागिकों के लिए पेंशन योजना।",
      "₹1000 / माह (10 वर्ष)", "वरिष्ठ नागरिक", "सभी", "elderly", False,
      "• 60+ वर्ष\n• LIC PMVVY\n• अधिकतम ₹15 लाख निवेश",
      "• आधार\n• बैंक खाता\n• PAN",
      "https://licindia.in/pm-vaya-vandana-yojana", "1800-425-9472"),
    s("राष्ट्रीय वयोश्री योजना", "BPL वरिष्ठ/दिव्यांग को assistive devices।",
      "₹7000 तक उपकरण", "वरिष्ठ नागरिक", "सभी", "elderly", False,
      "• 60+ वर्ष BPL\n• विकलांगता (यदि)\n• ALIMCO",
      "• BPL\n• आधार\n• विकलांगता प्रमाण (यदि)",
      "https://alimco.in", "1800-180-1234"),
    s("वरिष्ठ pension बीमा योजना (VPBY)", "60+ के लिए pension बीमा।",
      "₹1000 / माह", "वरिष्ठ नागरिक", "सभी", "elderly", False,
      "• 60+ वर्ष\n• LIC VPBY\n• अधिकतम ₹15 लाख",
      "• आधार\n• PAN\n• बैंक",
      "https://licindia.in", "1800-425-9472"),
    s("राजस्थान वरिष्ठ नागरिक तीर्थ यात्रा", "वरिष्ठ नागरिकों को मुफ्त तीर्थ यात्रा।",
      "निःशुल्क यात्रा", "वरिष्ठ नागरिक", "राजस्थान", "elderly", False,
      "• 60+ राजस्थान निवासी\n• BPL/सामान्य\n• राज्य योजना",
      "• आधार\n• निवास प्रमाण\n• फोटो",
      "https://sje.rajasthan.gov.in", "141-222-7272"),
    s("महाराष्ट्र वरिष्ठ नागरिक पेंशन", "MH senior citizen pension।",
      "₹600-1800 / माह", "वरिष्ठ नागरिक", "महाराष्ट्र", "elderly", False,
      "• 65+ Maharashtra\n• BPL\n• Sanjay Gandhi Niradhar",
      "• Aadhaar\n• BPL\n• Bank",
      "https://sjsa.maharashtra.gov.in", "1800-120-8040"),

    # स्वास्थ्य
    s("आyushman भारत PM-JAY", "₹5 लाख तक मुफ्त अस्पताल उपचार।",
      "₹5 लाख / परिवार / वर्ष", "स्वास्थ्य", "सभी", "health", True,
      "• SECC 2011 लाभार्थी\n• या राज्य योजना पात्र\n• PM-JAY कार्ड",
      "• आधार\n• Ration/SECC\n• संबंध प्रमाण",
      "https://pmjay.gov.in", "14555 / 1800-111-565"),
    s("राष्ट्रीय स्वास्थ्य मिशन", "प्राथमिक स्वास्थ्य सेवाएँ।",
      "निःशुल्क/सब्सिडी", "स्वास्थ्य", "सभी", "health", True,
      "• सभी नागरिक\n• PHC/CHC\n• राज्य NHM",
      "• आधार\n• संबंधित चिकित्सा दस्तावेज",
      "https://nhm.gov.in", "104"),
    s("PM राष्ट्रीय Dialysis कार्यक्रम", "मुफ्त Dialysis सुविधा।",
      "₹900 / सत्र तक", "स्वास्थ्य", "सभी", "health", False,
      "• Kidney रोगी\n• PMNDP केंद्र\n• BPL/सामान्य",
      "• डॉक्टर प्रमाण\n• आधार\n• BPL (यदि)",
      "https://nhm.gov.in", "104"),
    s("जan औषधi योजना", "सस्ती generic दवाएँ।",
      "50-90% सस्ती", "स्वास्थ्य", "सभी", "health", True,
      "• सभी नागरिक\n• Jan Aushadhi Kendra\n• डॉक्टर prescription",
      "• Prescription\n• आधार (कुछ केंद्र)",
      "https://janaushadhi.gov.in", "1800-180-8080"),
    s("मission Indradhanush", "बच्चों का पूर्ण टीकाकरण।",
      "निःशुल्क टीके", "स्वास्थ्य", "सभी", "health", True,
      "• 0-2 वर्ष बच्चे\n• गर्भवती महिलाएँ\n• PHC/AWC",
      "• MCP/Immunization card\n• आधार",
      "https://nhm.gov.in/mission-indradhanush", "104"),
    s("राष्ट्रीय बाल स्वास्थ्य कार्यक्रम", "0-18 वर्ष बच्चों की स्वास्थ्य जाँच।",
      "निःशुल्क", "स्वास्थ्य", "सभी", "health", False,
      "• 0-18 वर्ष\n• स्कूल/ANGANWADI\n• RBSK",
      "• आधार\n• स्कूल ID",
      "https://nhm.gov.in/rbsk", "104"),
    s("राजस्थान चिरंजीवी स्वास्थ्य बीमा", "Rajasthan universal health insurance।",
      "₹10 लाख / परिवार", "स्वास्थ्य", "राजस्थान", "health", True,
      "• Rajasthan resident\n• Chiranjeevi card\n• All families",
      "• Aadhaar\n• Rajasthan domicile",
      "https://chiranjeevi.rajasthan.gov.in", "1800-180-6127"),
    s("मध्य प्रदेश लाडli Laxmi (health related - use MP Swasthya)",
      "MP health scheme", "स्वास्थ्य", "मध्य प्रदेश", "health", False,
      "• MP resident\n• Ayushman/MP scheme",
      "• Aadhaar\n• MP domicile",
      "https://mphealth.mp.gov.in", "104"),
    s("गuजरात Mukhyamantri Amrutam", "Gujarat health for BPL।",
      "₹5 लाख", "स्वास्थ्य", "गुजरात", "health", True,
      "• BPL Gujarat\n• MA card\n• MAA Vatsalya",
      "• BPL\n• Aadhaar",
      "https://ma.yojana.gujarat.gov.in", "1800-233-2222"),
    s("महाराष्ट्र Mahatma Jyotiba Phule Jan Arogya", "MH state health (now PM-JAY integrated)।",
      "₹1.5-5 लाख", "स्वास्थ्य", "महाराष्ट्र", "health", False,
      "• Maharashtra BPL\n• MJPJAY card",
      "• Aadhaar\n• Ration card",
      "https://www.jeevandayee.gov.in", "155 388"),

    # Fix bad MP entry
]

# Replace bad entries
more[7] = s("मध्य प्रदेश स्वास्थ्य योजना", "MP में आयुषman/राज्य स्वास्थ्य सेवाएँ।",
      "₹5 लाख तक", "स्वास्थ्य", "मध्य प्रदेश", "health", False,
      "• MP निवासी\n• Ayushman/MP card",
      "• आधार\n• MP domicile",
      "https://mphealth.mp.gov.in", "104")

# व्यवसाय
business = [
    s("प्रधानमंत्री मudra योजना", "छोटे व्यवसायों को ऋण।",
      "₹50000-10 लाख", "व्यवसाय", "सभी", "business", True,
      "• भारतीय नागरिक\n• 18+ वर्ष\n• Shishu/Kishore/Tarun",
      "• Aadhaar/PAN\n• Business proof\n• Bank account",
      "https://www.mudra.org.in", "1800-180-1111"),
    s("Stand Up India", "SC/ST/Mahila entrepreneurs को ऋण।",
      "₹10 लाख-1 करोड़", "व्यवसाय", "सभी", "business", True,
      "• SC/ST/Mahila\n• Greenfield enterprise\n• 18+ years",
      "• Caste certificate\n• Aadhaar\n• Project report",
      "https://www.standupmitra.in", "1800-180-1111"),
    s("Startup India", "Startup registration और tax benefits।",
      "Tax exemption + funding", "व्यवसाय", "सभी", "business", True,
      "• Registered startup\n• DPIIT recognition\n• Innovation focused",
      "• Company registration\n• PAN\n• Pitch deck",
      "https://www.startupindia.gov.in", "1800-115-565"),
    s("PM Vishwakarma Yojana", "Traditional artisans को skill + loan।",
      "₹3 लाख तक", "व्यवसाय", "सभी", "business", True,
      "• 18+ traditional artisan\n• 18 trades covered\n• PM Vishwakarma portal",
      "• Aadhaar\n• Trade proof\n• Bank account",
      "https://pmvishwakarma.gov.in", "1800-113-333"),
    s("PM FME Scheme", "Micro food processing enterprises।",
      "₹10 लाख तक", "व्यवसाय", "सभी", "business", False,
      "• Individual/FPO/FPC\n• Food processing\n• PM FME portal",
      "• Aadhaar\n• Business plan\n• Bank",
      "https://mofpi.nic.in/pmfme", "1800-180-1551"),
    s("PMEGP", "Khadi Village Industries loan।",
      "₹25 लाख (manufacturing)", "व्यवसाय", "सभी", "business", True,
      "• 18+ years\n• 8th pass (manufacturing)\n• KVIC/KVIB/DIC",
      "• EDP certificate\n• Aadhaar\n• Project report",
      "https://www.kviconline.gov.in/pmegp", "1800-180-6763"),
    s("ASPIRE Scheme", "Agro rural enterprises।",
      "₹1 crore LFA", "व्यवसाय", "सभी", "business", False,
      "• Agro enterprises\n• Rural areas\n• MSME",
      "• Aadhaar\n• Business plan",
      "https://msme.gov.in/aspire", "1800-180-6763"),
    s("Coir Udyami Yojana", "Coir industry entrepreneurs।",
      "₹10 लाख + working capital", "व्यवसाय", "सभी", "business", False,
      "• Coir industry\n• Individual/SHG/Cooperative\n• Coir Board",
      "• Aadhaar\n• Project report\n• Land documents",
      "https://coirboard.gov.in", "0484-235-1807"),
    s("Credit Guarantee Fund Trust (CGTMSE)", "Collateral-free MSME loans।",
      "₹2 crore guarantee", "व्यवसाय", "सभी", "business", False,
      "• MSME\n• New/existing\n• Member lending institution",
      "• Udyam registration\n• Aadhaar\n• Business proof",
      "https://www.cgtmse.in", "1800-222-659"),
    s("Rajasthan MSME Scheme", "Rajasthan small business support।",
      "State subsidy", "व्यवसाय", "राजस्थान", "business", False,
      "• Rajasthan MSME\n• Udyam registered",
      "• Udyam\n• Aadhaar\n• Domicile",
      "https://msme.rajasthan.gov.in", "141-222-7272"),
]

# दिव्यांग
disability = [
    s("ADIP Scheme", "Assistive devices for disabled।",
      "₹10000+ devices", "दिव्यांग", "सभी", "disability", True,
      "• 40%+ disability\n• BPL priority\n• ALIMCO/DDRC",
      "• Disability certificate\n• Aadhaar\n• BPL (if applicable)",
      "https://disabilityaffairs.gov.in/adip", "1800-180-1234"),
    s("NHFDC Loan Scheme", "Disabled persons loan for self-employment।",
      "₹50 lakh max", "दिव्यांग", "सभी", "disability", True,
      "• 40%+ disability\n• 18+ years\n• NHFDC channel partner",
      "• Disability certificate\n• Aadhaar\n• Project report",
      "https://www.nhfdc.nic.in", "1800-11-4514"),
    s("Unique Disability ID (UDID)", "Single ID for PwD।",
      "Free card", "दिव्यांग", "सभी", "disability", True,
      "• Person with disability\n• Medical assessment\n• UDID portal",
      "• Aadhaar\n• Medical certificate\n• Photo",
      "https://www.swavlambancard.gov.in", "1800-180-1234"),
    s("DDRC Scheme", "Disabled rehabilitation centres।",
      "Free services", "दिव्यांग", "सभी", "disability", False,
      "• PwD\n• DDRC centre\n• Assessment",
      "• Disability certificate\n• Aadhaar",
      "https://disabilityaffairs.gov.in", "1800-180-1234"),
    s("Accessible India Campaign", "Accessible public infrastructure।",
      "Infrastructure access", "दिव्यांग", "सभी", "disability", False,
      "• PwD beneficiaries\n• Public buildings\n• Sugamya Bharat",
      "• Disability certificate\n• Aadhaar",
      "https://accessibleindia.gov.in", "1800-180-1234"),
    s("National Scholarship for PwD", "Disabled students scholarship।",
      "₹2500-3000/month", "दिव्यांग", "सभी", "disability", False,
      "• 40%+ disability\n• Class 9 to PG\n• Income limit",
      "• Disability certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Rajasthan Divyang Scooty Yojana", "Free scooty for disabled in Rajasthan।",
      "Free scooty", "दिव्यांग", "राजस्थान", "disability", False,
      "• 40%+ disability\n• Rajasthan resident\n• 18+ years",
      "• Disability certificate\n• Aadhaar\n• Domicile",
      "https://sje.rajasthan.gov.in", "141-222-7272"),
    s("Maharashtra Manav Vikas Disabled Scheme", "MH disability support।",
      "State benefits", "दिव्यांग", "महाराष्ट्र", "disability", False,
      "• PwD Maharashtra\n• State scheme",
      "• Disability certificate\n• Aadhaar",
      "https://sjsa.maharashtra.gov.in", "1800-120-8040"),
]

# अल्पसंख्यक
minority = [
    s("Pre Matric Scholarship (Minorities)", "Class 1-10 minority students।",
      "₹1000/year + hostel", "अल्पसंख्यक", "सभी", "minority", True,
      "• Muslim/Christian/Sikh/Buddhist/Parsi/Jain\n• 50%+ marks\n• Income ₹1 lakh",
      "• Minority certificate\n• Marksheet\n• Aadhaar\n• Income proof",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Post Matric Scholarship (Minorities)", "Class 11 to PG minority students।",
      "₹3000-12000/year", "अल्पसंख्यक", "सभी", "minority", True,
      "• Minority community\n• 50%+ marks\n• Income ₹2 lakh",
      "• Minority certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Maulana Azad National Fellowship", "Minority MPhil/PhD fellowship।",
      "₹31000-35000/month", "अल्पसंख्यक", "सभी", "minority", True,
      "• Minority community\n• MPhil/PhD\n• UGC NET/JRF",
      "• Minority certificate\n• NET certificate\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Padho Pardesh Scheme", "Interest subsidy on education loan abroad।",
      "Interest subsidy", "अल्पसंख्यक", "सभी", "minority", False,
      "• Minority\n• Education loan\n• Masters/PhD abroad",
      "• Minority certificate\n• Loan documents\n• Admission letter",
      "https://www.nmdfc.org/padho-pardesh", "011-2464-4818"),
    s("Nai Manzil Scheme", "Minority youth skill training।",
      "Free training + stipend", "अल्पसंख्यक", "सभी", "minority", False,
      "• Minority youth 17-35\n• School dropout\n• Skill training",
      "• Minority certificate\n• Aadhaar\n• Age proof",
      "https://www.minorityaffairs.gov.in", "011-2464-4818"),
    s("USTTAD Scheme", "Traditional artisan minority communities।",
      "Skill + market link", "अल्पसंख्यक", "सभी", "minority", False,
      "• Minority artisan\n• Traditional craft\n• USTTAD hub",
      "• Minority certificate\n• Craft proof\n• Aadhaar",
      "https://www.minorityaffairs.gov.in", "011-2464-4818"),
    s("NMDFC Term Loan", "Minority business loan।",
      "₹30 lakh max", "अल्पसंख्यक", "सभी", "minority", False,
      "• Minority\n• Self-employment\n• NMDFC channel partner",
      "• Minority certificate\n• Aadhaar\n• Project report",
      "https://www.nmdfc.org", "011-2464-4818"),
    s("Seekho aur Kamao", "Minority youth placement linked skill।",
      "Stipend + placement", "अल्पसंख्यक", "सभी", "minority", False,
      "• Minority 14-35\n• Skill training\n• Placement",
      "• Minority certificate\n• Aadhaar\n• Education proof",
      "https://www.minorityaffairs.gov.in", "011-2464-4818"),
]

# SC/ST/OBC
caste = [
    s("Post Matric Scholarship (SC)", "SC students post matric scholarship।",
      "₹1200-1500/month", "SC/ST/OBC", "सभी", "caste", True,
      "• SC category\n• Post matric\n• Income limit",
      "• Caste certificate\n• Marksheet\n• Aadhaar\n• Income proof",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Pre Matric Scholarship (SC)", "SC students class 9-10।",
      "₹350/month + books", "SC/ST/OBC", "सभी", "caste", True,
      "• SC\n• Class 9-10\n• Parent income limit",
      "• Caste certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("National Fellowship for SC", "SC MPhil/PhD fellowship।",
      "₹31000-35000/month", "SC/ST/OBC", "सभी", "caste", True,
      "• SC\n• MPhil/PhD\n• UGC NET qualified",
      "• Caste certificate\n• NET certificate\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("National Overseas Scholarship (SC)", "SC students study abroad।",
      "Full funding", "SC/ST/OBC", "सभी", "caste", False,
      "• SC\n• Masters/PhD abroad\n• 55%+ marks",
      "• Caste certificate\n• Admission letter\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Post Matric Scholarship (OBC)", "OBC post matric scholarship।",
      "₹750-1200/month", "SC/ST/OBC", "सभी", "caste", True,
      "• OBC\n• Post matric\n• Income ₹1.5 lakh (parent)",
      "• OBC certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Pre Matric Scholarship (OBC)", "OBC class 9-10 scholarship।",
      "₹500/month", "SC/ST/OBC", "सभी", "caste", False,
      "• OBC\n• Class 9-10\n• Income limit",
      "• OBC certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("National Fellowship for OBC", "OBC MPhil/PhD fellowship।",
      "₹25000-28000/month", "SC/ST/OBC", "सभी", "caste", False,
      "• OBC\n• MPhil/PhD\n• NET qualified",
      "• OBC certificate\n• NET\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Dr Ambedkar Post Matric (EBC)", "EBC students scholarship।",
      "₹750-1200/month", "SC/ST/OBC", "सभी", "caste", False,
      "• EBC (non-creamy layer)\n• Post matric\n• Income limit",
      "• Income certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Top Class Education (SC)", "SC students top institutions।",
      "Full tuition + hostel", "SC/ST/OBC", "सभी", "caste", True,
      "• SC\n• Class 12 pass\n• Top class institution",
      "• Caste certificate\n• 12th marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Post Matric Scholarship (ST)", "ST post matric scholarship।",
      "₹1200-1500/month", "SC/ST/OBC", "सभी", "caste", True,
      "• ST\n• Post matric\n• Income limit",
      "• ST certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("National Fellowship for ST", "ST MPhil/PhD fellowship।",
      "₹31000-35000/month", "SC/ST/OBC", "सभी", "caste", False,
      "• ST\n• MPhil/PhD\n• NET qualified",
      "• ST certificate\n• NET\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
    s("Pre Matric Scholarship (ST)", "ST class 9-10 scholarship।",
      "₹350/month", "SC/ST/OBC", "सभी", "caste", False,
      "• ST\n• Class 9-10",
      "• ST certificate\n• Marksheet\n• Aadhaar",
      "https://scholarships.gov.in", "0120-6619540"),
]

# State specific schemes to reach 100
state_schemes = [
    s("मुख्यमंत्री राजshri योजना", "Rajasthan girl child incentive।",
      "₹50000+", "महिला", "राजस्थान", "woman", True,
      "• Rajasthan resident\n• Girl child\n• Institutional delivery",
      "• Aadhaar\n• Birth certificate\n• Bank account",
      "https://rajshree.rajasthan.gov.in", "181"),
    s("लadli Laxmi Yojana (MP)", "MP girl child savings scheme।",
      "₹1.18 lakh", "महिला", "मध्य प्रदेश", "woman", True,
      "• MP resident\n• Girl born after 2006\n• Family planning",
      "• Birth certificate\n• Aadhaar\n• Bank",
      "https://ladlilaxmi.mp.gov.in", "0755-255-0808"),
    s("Vahli Dikri Yojana (Gujarat)", "Gujarat girl child assistance।",
      "₹1 lakh+", "महिला", "गुजरात", "woman", True,
      "• Gujarat resident\n• Girl child\n• Income limit",
      "• Birth certificate\n• Aadhaar\n• Income proof",
      "https://vahlidikri.gujarat.gov.in", "1800-233-4444"),
    s("Majhi Kanya Bhagyashree (MH)", "Maharashtra girl child scheme।",
      "₹50000+", "महिला", "महाराष्ट्र", "woman", False,
      "• Maharashtra\n• Girl child\n• BPL/family limit",
      "• Birth certificate\n• Aadhaar\n• Ration card",
      "https://wcd.maharashtra.gov.in", "1800-120-8040"),
    s("Mukhyamantri Kanya Sumangala (UP)", "UP girl child welfare।",
      "₹15000 (6 installments)", "महिला", "उत्तर प्रदेश", "woman", True,
      "• UP resident\n• Girl child\n• Max 2 daughters",
      "• Birth certificate\n• Aadhaar\n• Bank",
      "https://mksy.up.gov.in", "0522-272-8888"),
    s("Rajasthan Kisan Loan Waiver", "Rajasthan farmer loan relief।",
      "Loan waiver", "किसान", "राजस्थान", "agriculture", False,
      "• Rajasthan farmer\n• Short term crop loan\n• State notified",
      "• Aadhaar\n• Loan documents\n• Land records",
      "https://krishi.rajasthan.gov.in", "1800-180-1551"),
    s("MP Mukhyamantri Kisan Kalyan", "MP farmer welfare।",
      "State benefits", "किसान", "मध्य प्रदेश", "agriculture", False,
      "• MP farmer\n• State scheme",
      "• Aadhaar\n• Land records",
      "https://mpkrishi.mp.gov.in", "0755-255-0808"),
    s("Gujarat Kisan Sarvoday Yojana", "Gujarat farmer electricity scheme।",
      "₹1500-3500/year", "किसान", "गुजरात", "agriculture", False,
      "• Gujarat farmer\n• Power connection\n• Agriculture",
      "• Aadhaar\n• Land records\n• Electricity bill",
      "https://agri.gujarat.gov.in", "1800-233-4444"),
    s("UP Mukhyamantri Abhyudaya", "UP free coaching for competitive exams।",
      "Free coaching", "छात्र", "उत्तर प्रदेश", "school", True,
      "• UP resident\n• Competitive exam aspirant\n• Registration",
      "• Aadhaar\n• Domicile\n• Education proof",
      "https://abhyudaya.up.gov.in", "0522-272-8888"),
    s("Rajasthan Indira Gandhi Scholarship", "Rajasthan merit scholarship।",
      "₹40000/year", "छात्र", "राजस्थान", "school", False,
      "• Rajasthan\n• Top 1000 in board\n• Higher education",
      "• Marksheet\n• Aadhaar\n• Domicile",
      "https://scholarship.rajasthan.gov.in", "141-222-7272"),
    s("UP Samajwadi Pension Yojana", "UP old age/widow pension।",
      "₹1000/month", "वरिष्ठ नागरिक", "उत्तर प्रदेश", "elderly", False,
      "• UP resident 60+\n• BPL\n• Widow/disabled also",
      "• Aadhaar\n• BPL\n• Age proof",
      "https://sspy-up.gov.in", "0522-272-8888"),
    s("MP Mukhyamantri Jan Kalyan (Sambal)", "MP BPL family benefits।",
      "₹1000/month + benefits", "रोजगार", "मध्य प्रदेश", "work", False,
      "• MP BPL\n• Sambal registration\n• Labour/worker",
      "• Aadhaar\n• BPL\n• Bank",
      "https://sambal.mp.gov.in", "0755-255-0808"),
]

# Combine all
all_schemes = (
    schemes[:8] +  # kisan central (first 8, skip bad one)
    schemes[9:19] +  # mahila central
    schemes[20:30] +  # student central
    schemes[31:39] +  # employment (skip duplicate bad)
    more +  # housing, senior, health
    business +
    disability +
    minority +
    caste +
    state_schemes
)

# Deduplicate by title and trim/pad to exactly 100
seen = set()
unique = []
for sch in all_schemes:
    if sch["title"] not in seen:
        seen.add(sch["title"])
        unique.append(sch)

print(f"Total unique schemes: {len(unique)}")

if len(unique) < 100:
    # Add more real schemes
    extras = [
        s("PM Suraksha Bima Yojana", "Accident insurance ₹2 lakh at ₹20/year।",
          "₹2 lakh cover", "स्वास्थ्य", "सभी", "health", False,
          "• 18-70 years\n• Bank account\n• Auto-debit ₹20",
          "• Aadhaar\n• Bank account",
          "https://www.jansuraksha.gov.in", "1800-180-1111"),
        s("PM Jeevan Jyoti Bima Yojana", "Life insurance ₹2 lakh at ₹436/year।",
          "₹2 lakh cover", "स्वास्थ्य", "सभी", "health", False,
          "• 18-50 years\n• Bank account\n• ₹436/year",
          "• Aadhaar\n• Bank account",
          "https://www.jansuraksha.gov.in", "1800-180-1111"),
        s("Atal Bhujal Yojana", "Groundwater management for farmers।",
          "Community benefit", "किसान", "सभी", "agriculture", False,
          "• Water stressed areas\n• Community participation\n• State implementation",
          "• Aadhaar\n• Community registration",
          "https://jalshakti-dowr.gov.in", "1800-180-1551"),
        s("National Livestock Mission", "Livestock development subsidy।",
          "Subsidy on livestock", "किसान", "सभी", "agriculture", False,
          "• Farmer/livestock owner\n• NLM scheme\n• State veterinary",
          "• Aadhaar\n• Livestock proof\n• Bank",
          "https://dahd.nic.in", "1800-180-1551"),
        s("UP Bhagya Lakshmi Yojana", "UP BPL girl child bond।",
          "₹50000 bond", "महिला", "उत्तर प्रदेश", "woman", False,
          "• UP BPL\n• Girl child\n• Max 2 daughters",
          "• BPL\n• Birth certificate\n• Aadhaar",
          "https://wcd.up.gov.in", "0522-272-8888"),
    ]
    for e in extras:
        if e["title"] not in seen and len(unique) < 100:
            seen.add(e["title"])
            unique.append(e)

# Trim to 100 if over
unique = unique[:100]

with open("../assets/json/schemes.json", "w", encoding="utf-8") as f:
    json.dump(unique, f, ensure_ascii=False, indent=2)

print(f"Written {len(unique)} schemes to schemes.json")
